language: node_js

node_js:
  - "8"
  - "7"

before_install:
  - sudo apt-get update
  - sudo apt-get install docker

install:
  - npm i mocha
  - npm i expect

script: npm i box-exec

deploy:
  provider: npm
  email: "akshit.grover2016@gmail.com"
  api_key: 
    secure: "bXXeNhBqmMC+UYf0dz5UpF5pu8szXCbhHkK74sCeG1SGl5MWn1/bbpvxXVwnXqUhdMEZuDziKTvN1A2e7kwRRGRkWu0Zm2uyHwchtkU6sqNOlXiLI5dtTieDdB/QGwfiEnSV7Sygs1pORL1qDJ0/debJtKBbCQ3xEzS4GS6jusAVsqwFH4ItKclfT8Icf4HCzXDdt0AVLHs/5VK7Q+EYnfCjanPS3QjCvOjRpQ5JV5j6fTy8lBtAwkv80vQ6h26NVsNr/2tHIio+evEdapDuXPpBmpgfcm4hgHoa7kxO9uoCIe0cJaOxmk5Isimd/vXzu5yfmBAgn+6RYa9LMy0FfMpFhWjdv5PkHZaYFUl86965FK91AVj03Xg4CYFd+vf8IcP7tHukmVq0xxjp5u/x/1YBKJiY5c8HUP3Nf9tgjUUGYmlwnrHWO0q3D8/aEaF1JGRi5eIUM6aqceH3lUrEAroPLbyqr+D9AXJMGu6VklyFb+lxp5J0Gwrjy8jkJEdG9qUtX8nRNLjMFz0O/2m3eYXwD9H1so/U+gpnj7YUEW6xTgqFpqaHjfbwsUYmW+CFJOKYrLh7RUNeD3d4/IzIadxxXCXvgnvmrMaZKlaP1bLbrxGnl4ytOKkhMVKSzOwtx5QqLOsqiAVXncQbyIIlEJoqf//8mNEUW1hUJZggU7w="

